### ISSUE TITLE
BitmapData as Worker parameter

### ISSUE THREAD

**Issue by jankroupa** [myflashlab/easyAS-Worker#1]
Hi, I'm trying to use your easyAS-Worker to encode BitmapData to ByteArray and then upload to server and I'm having trouble with passing the BitmapData variable to the worker function.

This is the function itself

``` actionscript
 public function encodeImageAndSave(bmpData:BitmapData, url:String):void
    {
        thisCommand = arguments.callee;
        //here is the encoding and uploading code
    } 
```

I'm calling the as shown in the example with the WorkerManager

``` actionscript
    var wm:WorkerManager;
    public function start(worker:Class):void
    {
        wm = new WorkerManager(worker, loaderInfo.bytes, this);
        wm.start();
        wm.addEventListener(Event.WORKER_STATE, onWorkerState);
    }

    private function onWorkerState(e:Event):void
    {
        if (wm.state == WorkerState.RUNNING)
        {
             wm.command("encodeImageAndSave", onProgress, onResult, imageToUpload, urlToCall);
        }
    }
```

But the encoding function didn't run at all and I'm getting Error #1034: Type Coercion failed: cannot convert Object@11bbbe3a1 to flash.display.BitmapData.

Am I doing something wrong or it's just not possible to pass BitmapData as parameter?

**Comment by myflashlab** [comment]
We are currently using `MessageChannel` mechanism for communicating between workers. that means, you can send String or Numbers between the threads. we will add shareable properties in future versions.

the easy solution you have right now is to serialize your Bitmap into a String mabe by using Base64 standards or something similar. and send the String to the worker. Then generate your BitmapData back from the incoming String.

**Comment by myflashlab** [comment]
to know better about what parameters you can send with the current mechanism, read this: http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/system/MessageChannel.html#send%28%29

> The object passed to the arg parameter can be almost any object. Other than the exceptions noted below, any object that is passed to the arg parameter is not passed by reference. Any changes made to the object in one worker after send() is called are not carried over to the other worker. The object is copied by serializing it to AMF3 format and deserializing it into a new object in the receiving worker when receive() is called. For this reason, any object that can't be serialized in AMF3 format, including display objects, can't be passed to the arg parameter. In order for a custom class to be passed properly, the class definition must be registered using the flash.net.registerClassAlias() function or [RemoteClass] metadata. With either technique the same alias must be used for both worker's versions of the class.

As mentioned in the documents, you can send shareable byteArrays using this method. (we have not tested this yet)

**Comment by jankroupa** [comment]
Thank you for your answer. I was afraid I couldn't use BitmapData as parameter.

My original thought was to use the worker to serialize the BitmapData into a String using Base64 and then upload it to server because it uses lots of resources on mobile and the UI freezes during the process. Asynchronous encoding did the job instead of the worker.

**Comment by ROBERT-MCDOWELL** [comment]
be aware that shareable byteArray have been disabled since flash/air version 30.x.x
to protect users from the spectre meltdown CPU security holes

**Comment by anthodb** [comment]
What do you suggest as shareable byteArray have been disabled.. Do you have a nice solution to pass bitmapdatas to worker without having to fully encode it in Base64? I mean I have huge bitmaps to handle, this process could kill the performances...

**Comment by ROBERT-MCDOWELL** [comment]
the only way for now is to use MessageChannel...
