### ISSUE TITLE
Workers

### ISSUE THREAD

**Issue by BenQ12345** [myflashlab/easyAS-Worker#7]
Hi, How to use Workers for individual code for example i want to use workers for Adds-on. How to call add-add-on function in workers can you send sample code

**Comment by BenQ12345** [comment]
Waiting for your reply........

**Comment by BenQ12345** [comment]
It's very urgent can you send sample code

**Comment by myflashlab** [comment]
We don't have a sample code other than the current one available on the repository. Also note that this is an opensource project and not related to the commercial ANEs.
